@include('layouts.header')
    @yield('login-section')
    @yield('csvUpload-section')
    @yield('imageUpload-section')
    @yield('changePassword-section')
    @yield('scripts')
@include('layouts.footer')